output "vpc_id" { value = aws_vpc.main.id }
output "public_subnet_ids" { value = [aws_subnet.public_a.id, aws_subnet.public_b.id] }
output "private_subnet_ids" { value = [aws_subnet.private_a.id, aws_subnet.private_b.id] }
output "db_subnet_ids" { value = [aws_subnet.db_a.id, aws_subnet.db_b.id] }
output "alb_arn" { value = aws_lb.main.arn }
output "alb_dns_name" { value = aws_lb.main.dns_name }
output "target_group_arn" { value = aws_lb_target_group.ecs.arn }
output "ecs_security_group_id" { value = aws_security_group.ecs.id }
output "db_security_group_id" { value = aws_security_group.db.id }
output "cache_security_group_id" { value = aws_security_group.cache.id }
output "vpc_endpoint_sg_id" { value = aws_security_group.vpc_endpoint.id }
